namespace: zedr
name: simple_netbox_inventory_plugin
version: 1.0.0
readme: README.md
authors:
  - Rigel Di Scala <rigel@redhat.com>
description: an example inventory plugin for NetBox
license:
  - GPL-3.0-or-later
license_file: ''
tags:
  - netbox
  - inventory
  - plugin
  - example
dependencies: {}
repository: https://github.com/zedr/simple_netbox_inventory_plugin
documentation: ''
homepage: https://github.com/zedr/simple_netbox_inventory_plugin
issues: https://github.com/zedr/simple_netbox_inventory_plugin/issues
